pipeline {
    agent any
    stages {
        stage('Run docker image') {
            steps {
                sh('docker push antonioazambuja/teste:latest')
                sh('docker run -d -p 8083:8080 antonioazambuja/teste:latest')
            }
        }
    }
}