pipeline {
   agent any
    stages {
        stage('jar file download') {
            steps {
                    rtServer (
                        id: "ArtifactoryJar",
                        url: "http://localhost:8081/artifactory",
                        username: env.ENV_JFROG_USER,
                        password: env.ENV_JFROG_PASSWORD
                    )

                    rtDownload (
                        serverId: "ArtifactoryJar",
                        spec:
                            """{
                              "files": [
                                {
                                  "pattern": "example-repo-local/",
                                  "target": "app.war"
                                }
                             ]
                            }"""
                    )
            }
        }
        stage('Packer file') {
            steps {
                sh('packer build -var-file=tasks/infra/variables.json tasks/infra/build.json')
            }
        }
    }
}
