- hosts: all
  become_user: sudo
  gather_facts: no

  pre_tasks:
    - name: apk update
      raw: apk update
    - name: install python3
      raw: apk add python3
    - name: install tar
      raw: apk add tar
    
  tasks:
    - name: Adicionando vars
      include_vars:
        file: vars.yml

    - name: Criando a pastas do tomcat
      file:
        path: /opt/apache-tomcat-9.0.24
        state: directory
    
    - name: download tomcat
      get_url:
        url: "{{ tomcat_archive_url }}"
        dest: "{{ tomcat_archive_dest }}"

    - name: Extraindo tomcat
      unarchive:
        src: "{{ tomcat_archive_dest }}"
        dest: /opt/apache-tomcat-9.0.24
        remote_src: yes

    - name: Copiar .war para pasta desafio-final
      copy:
        src: ../../app.war
        dest: /opt/apache-tomcat-9.0.24/webapps/app.war
