pipeline {
   agent any
    stages {
        stage('Build') {
            steps {
		sh '''
                   cd antonio-azambuja/temafinal1-cloud/
		   gradle build
                   '''
            }
        }
        stage('Publish .jar to Jfrog') {
            steps {
                rtServer (
                    id: "ArtifactoryJar",
                    url: "http://localhost:8081/artifactory",
                    username: env.ENV_JFROG_USER,
                    password: env.ENV_JFROG_PASSWORD
                )

                rtUpload (
                    serverId: "ArtifactoryJar",
                    spec:
                        """{
                          "files": [
                            {
                              "pattern": "antonio-azambuja/temafinal1-cloud/build/libs/*.war",
                              "target": "example-repo-local/app.war"
                            }
                         ]
                        }"""
                )
            }
        }
    }
}
